spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/software_engineering?serverTimezone=UTC
    schema:
      - classpath:sql/department.sql
      - classpath:sql/employee.sql
    initialization-mode: always

#hej
#dev1